# Generated by Django 6.0.5 on 2026-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Farmer', 'Farmer'), ('Consumer', 'Consumer'), ('Buyer', 'Buyer')], default='Consumer', max_length=10),
        ),
    ]
