# Generated by Django 6.0.5 on 2026-05-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_note',
            field=models.CharField(blank=True, help_text='Contact info or note (e.g. cooperative phone number)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Farmer', 'Farmer'), ('Consumer', 'Consumer'), ('Buyer', 'Buyer'), ('Cooperative', 'Cooperative')], default='Consumer', max_length=15),
        ),
    ]
